[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci --production=false']

[phases.build]
cmds = ['chmod +x debug-build.sh', './debug-build.sh', 'npm run build']

[start]
cmd = 'node .next/standalone/server.js'