version: "3.9"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: urukundo-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    # If your Next.js app rewrites to a backend, set that backend URL here
    # and read it in next.config or via process.env
    # - BACKEND_URL=http://backend:8080
    # depends_on:
    #   - backend
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8080:8080"
