[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd frontend && npm ci --production=false']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && node .next/standalone/server.js'