[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['cd frontend && npm ci --production=false']

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd frontend && PORT=$PORT HOSTNAME=0.0.0.0 node .next/standalone/server.js'

[variables]
PORT = '8080'
HOSTNAME = '0.0.0.0'