[build]
builder = "nixpacks"

[deploy]
startCommand = "cd frontend && PORT=$PORT HOSTNAME=0.0.0.0 node .next/standalone/server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "8080"
HOSTNAME = "0.0.0.0"